# Generated by Django 3.2.6 on 2021-08-09 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='csv_uploads/')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'yet_to_start'), (2, 'in_progress'), (3, 'completed'), (4, 'failed')], default=0)),
            ],
            options={
                'db_table': 'csv_uploads',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('education', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=5)),
                ('occupation', models.CharField(max_length=100)),
                ('income', models.FloatField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('loan_account_number', models.PositiveIntegerField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_date', models.DateField()),
                ('lrn', models.PositiveIntegerField()),
                ('tenor', models.FloatField()),
                ('adv_emi', models.IntegerField()),
                ('mob', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_pincode', models.PositiveIntegerField(max_length=6)),
                ('office_landmark', models.CharField(max_length=255)),
                ('office_address_1', models.CharField(max_length=255)),
                ('office_address_2', models.CharField(max_length=255)),
                ('office_address_3', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.PositiveIntegerField(max_length=6)),
                ('landmark', models.CharField(max_length=255)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(max_length=255)),
                ('address_3', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.customer')),
            ],
        ),
        migrations.CreateModel(
            name='BranchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
                ('branch_code', models.PositiveIntegerField(max_length=11)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.customer')),
            ],
        ),
    ]
