TASK_STATUS_YET_TO_START = 1
TASK_STATUS_IN_PROGRESS = 2
TASK_STATUS_COMPLETED = 3
TASK_STATUS_FAILED = 4

TASK_STATUS_YET_TO_START_STR = "yet_to_start"
TASK_STATUS_IN_PROGRESS_STR = "in_progress"
TASK_STATUS_COMPLETED_STR = "completed"
TASK_STATUS_FAILED_STR = "failed"
